name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Install Allure command line
      run: npm install -g allure-commandline --save-dev

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Generate Allure report
      if: always()
      run: npm run allure-collect

    - name: Upload test results to Github Pages
      uses: actions/upload-artifact@v3
      with: 
        name: playwright-results
        path: allure-report

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        # gh_pages: gh-pages
        allure_report: allure-report
        # allure_history: allure-history
        # keep_reports: 20

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

    # - name: Publish Allure report
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with: 
    #     folder: allure-report
    
